services:
  - type: web
    name: gigsama-backend
    env: python
    region: oregon
    plan: free
    rootDir: model_backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn dual_backend:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: MODAL_INFERENCE_URL
        value: https://affum3331--gigsama-backend-fastapi-app.modal.run
      - key: PYTHON_VERSION
        value: 3.11.0
    healthCheckPath: /health
